### ISSUE TITLE
--no-tweets gets stuck when plotting route

### ISSUE THREAD

**Issue by rhk** [juusomer/nopeusbotti#3]
Hey there & awesome use of OpenData!!

```
rhk@rhk-VirtualBox:~/nopeusbotti/nopeusbotti$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
rhk@rhk-VirtualBox:~/nopeusbotti/nopeusbotti$ poetry --version
Poetry (version 1.2.0)
rhk@rhk-VirtualBox:~/nopeusbotti/nopeusbotti$ python3 --version
Python 3.10.4



rhk@rhk-VirtualBox:~/nopeusbotti/nopeusbotti$ poetry run nopeusbotti   --speed-limit 10   --north 60.2246 --south 60.2211 --east 24.7987 --west 24.7842 --route 114 --route 215 --route 200 --route 214 --route 239 --route 532 --route 224 --route 227 --no-tweets
2022-09-13 14:12:06,207 Run with --no-tweets: only producing figures, will not send any tweets
2022-09-13 14:12:06,360 Client connected (rc = 0)
2022-09-13 14:12:06,986 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2114/#
2022-09-13 14:12:07,474 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2215/#
2022-09-13 14:12:07,986 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2200/#
2022-09-13 14:12:08,504 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2214/#
2022-09-13 14:12:09,092 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2239/#
2022-09-13 14:12:09,606 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2532/#
2022-09-13 14:12:10,230 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2224/#
2022-09-13 14:12:10,778 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2227/#
2022-09-13 14:13:28,906 (6, 454, '2022-09-13', '13:29') has entered the monitored area
2022-09-13 14:13:50,843 (22, 1154, '2022-09-13', '13:34') has entered the monitored area
2022-09-13 14:14:01,785 (22, 1128, '2022-09-13', '13:45') has entered the monitored area
2022-09-13 14:15:02,031 (6, 454, '2022-09-13', '13:29') has left the area, plotting route
^C
Aborted!
rhk@rhk-VirtualBox:~/nopeusbotti/nopeusbotti$

```
Nothing happens for several minutes, no image is created (at least in any of nopeusbotti folders) and no further tracking is done. Tried this several times. Also tried with the code in the pending pull request -> the --csv-only option works and the csv log file is created successfully so the used parameters should be OK, I assume.

Any pointers what could cause this?

r

**Comment by rhk** [comment]
Ah, seems to work. Just takes a long time at least on this virtual machine :D

rhk@rhk-VirtualBox:~/nopeusbotti/nopeusbotti$ poetry run nopeusbotti   --speed-limit 20   --north 60.2246 --south 60.2211 --east 24.7987 --west 24.7842 --route 114 --route 215 --route 200 --route 214 --route 239 --route 532 --route 224 --route 227 --no-tweets
2022-09-13 14:21:25,687 Run with --no-tweets: only producing figures, will not send any tweets
2022-09-13 14:21:25,859 Client connected (rc = 0)
2022-09-13 14:21:26,500 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2114/#
2022-09-13 14:21:27,161 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2215/#
2022-09-13 14:21:27,767 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2200/#
2022-09-13 14:21:28,306 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2214/#
2022-09-13 14:21:28,888 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2239/#
2022-09-13 14:21:29,539 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2532/#
2022-09-13 14:21:30,090 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2224/#
2022-09-13 14:21:31,181 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2227/#
2022-09-13 14:21:31,578 (12, 1918, '2022-09-13', '13:53') has entered the monitored area
2022-09-13 14:21:31,747 (22, 900, '2022-09-13', '13:44') has entered the monitored area
2022-09-13 14:21:41,861 (6, 450, '2022-09-13', '14:18') has entered the monitored area
2022-09-13 14:21:57,742 (22, 900, '2022-09-13', '13:44') has left the area, plotting route
2022-09-13 14:26:18,484 Saved plot to 64863248-c259-4a8f-b15f-e30b088a099e.png
2022-09-13 14:26:18,485 (12, 1918, '2022-09-13', '13:53') has left the area, plotting route
2022-09-13 14:32:51,685 Saved plot to 674318f9-f11c-44bc-a960-c76cab2bdb47.png
2022-09-13 14:32:52,820 Client connected (rc = 0)
2022-09-13 14:32:53,361 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2114/#
2022-09-13 14:32:53,978 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2215/#
2022-09-13 14:32:54,626 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2200/#
2022-09-13 14:32:55,205 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2214/#
2022-09-13 14:32:55,780 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2239/#
2022-09-13 14:32:56,351 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2532/#
2022-09-13 14:32:56,955 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2224/#
2022-09-13 14:32:57,553 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2227/#
2022-09-13 14:32:58,362 (12, 1402, '2022-09-13', '14:08') has entered the monitored area
2022-09-13 14:32:58,770 (22, 1166, '2022-09-13', '13:54') has entered the monitored area
2022-09-13 14:32:58,809 (6, 450, '2022-09-13', '14:18') has left the area, plotting route
2022-09-13 14:32:59,000 Saved plot to 6ddec04c-0aaf-42c8-8733-c588042a98b3.png
2022-09-13 14:33:29,792 (6, 462, '2022-09-13', '13:54') has entered the monitored area
2022-09-13 14:34:07,198 (12, 1402, '2022-09-13', '14:08') has left the area, plotting route



// retried with 3CPU's & 10G RAM - still takes a very long time to make a single plot. Most of the time nothing happens on CPU nor RAM -> I don't know what's the bottle neck here.

8 minutes here, CPU usage at 4%. I stopped it at 20 minutes.

![kuva](https://user-images.githubusercontent.com/404543/189895177-939e0aaa-cc56-468e-93a2-c481855c21a8.png)

**Comment by rhk** [comment]
Reopening. There's propably something that someone would want to have a look at.

Looks like that it took about 70 minutes to create a single plot - and then receiving error 500 from digitransit was too much and the bot crashed.


``rhk@rhk-VirtualBox:~/nopeusbotti/nopeusbotti$ poetry run nopeusbotti   --speed-limit 20   --north 60.2246 --south 60.2214 --east 24.8010 --west 24.7842 --route 114 --route 215 --route 200 --route 214 --route 239 --route 532 --route 224 --route 227 --no-tweets
2022-09-13 15:10:42,664 Run with --no-tweets: only producing figures, will not send any tweets
2022-09-13 15:10:42,823 Client connected (rc = 0)
2022-09-13 15:10:43,415 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2114/#
2022-09-13 15:10:43,999 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2215/#
2022-09-13 15:10:44,881 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2200/#
2022-09-13 15:10:46,289 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2214/#
2022-09-13 15:10:46,967 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2239/#
2022-09-13 15:10:47,470 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2532/#
2022-09-13 15:10:48,008 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2224/#
2022-09-13 15:10:48,742 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2227/#
2022-09-13 15:10:49,024 (6, 445, '2022-09-13', '14:28') has entered the monitored area
2022-09-13 15:10:49,883 (22, 1234, '2022-09-13', '14:38') has entered the monitored area
2022-09-13 15:11:59,942 (22, 1234, '2022-09-13', '14:38') has left the area, plotting route
2022-09-13 16:21:53,727 Saved plot to 215929c5-98da-4262-82a2-06237daddf2f.png
2022-09-13 16:22:55,316 Client connected (rc = 0)
2022-09-13 16:22:55,986 Subscribing to /hfp/v2/journey/ongoing/vp/+/+/+/2114/#
Traceback (most recent call last):
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/gql/transport/aiohttp.py", line 304, in raise_response_error
    resp.raise_for_status()
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.digitransit.fi/routing/v1/routers/hsl/index/graphql')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/rhk/nopeusbotti/nopeusbotti/cli.py", line 69, in main
    client.loop_forever()
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/home/rhk/nopeusbotti/nopeusbotti/bot.py", line 71, in on_connect
    topic = self.get_mqtt_topic(route)
  File "/home/rhk/nopeusbotti/nopeusbotti/bot.py", line 55, in get_mqtt_topic
    result = client.execute(query)
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/gql/client.py", line 388, in execute
    data = loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/gql/client.py", line 285, in execute_async
    return await session.execute(
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/gql/client.py", line 1220, in execute
    result = await self._execute(
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/gql/client.py", line 1126, in _execute
    result = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/gql/transport/aiohttp.py", line 326, in execute
    await raise_response_error(resp, 'No "data" or "errors" keys in answer')
  File "/home/rhk/.cache/pypoetry/virtualenvs/nopeusbotti-Q_9Pjy1C-py3.10/lib/python3.10/site-packages/gql/transport/aiohttp.py", line 306, in raise_response_error
    raise TransportServerError(str(e), e.status) from e
gql.transport.exceptions.TransportServerError: 500, message='Internal Server Error', url=URL('https://api.digitransit.fi/routing/v1/routers/hsl/index/graphql')
``

**Comment by juusomer** [comment]
For what it's worth, I had no issue running your command:

![4ac2caa5-483d-4230-b81f-2c9820ce978a](https://user-images.githubusercontent.com/20384903/189966508-aacaa7b0-7b31-44c7-8ce3-66e7e15ceafb.png)

![26ca5253-21d3-49e5-81c2-a884b4131603](https://user-images.githubusercontent.com/20384903/189966516-1a36a0f7-cf14-48b4-aab0-19b5461496f6.png)

...and yeah, it looks like a good use case for the bot.

Since there are no CPU or RAM woes, I suspect something may be off with getting the basemap for the map plot over the internet.

**Comment by rhk** [comment]
At some point it started to run smoothly:

2022-09-13 21:05:37,079 (6, 881, '2022-09-13', '20:30') has entered the monitored area
2022-09-13 21:05:50,532 (6, 461, '2022-09-13', '21:01') has left the area, plotting route
2022-09-13 21:05:50,823 Saved plot to 0b6b814a-115a-4a27-8aaf-d0491b02b6e1.png
2022-09-13 21:06:21,543 (6, 457, '2022-09-13', '21:03') has entered the monitored area
2022-09-13 21:06:22,360 (6, 776, '2022-09-13', '21:01') has left the area, plotting route
2022-09-13 21:06:22,656 Saved plot to 74c956f4-43c4-4756-b821-18f792780619.png
2022-09-13 21:06:37,937 (22, 1035, '2022-09-13', '21:03') has left the area, plotting route
2022-09-13 21:06:38,297 Saved plot to 7c9cecb4-6147-4344-a850-730e887a0ca1.png
2022-09-13 21:06:44,288 (6, 881, '2022-09-13', '20:30') has left the area, plotting route
2022-09-13 21:06:44,642 Saved plot to 9ee554f9-89f1-4abd-b5a5-4c3859fce4be.png
2022-09-13 21:07:31,565 (6, 457, '2022-09-13', '21:03') has left the area, plotting route
2022-09-13 21:07:31,881 Saved plot to 78bbd39e-171b-450e-bb5e-c81bb9739476.png


and has so far been running smoothly. So it's possible, that there's been some glitches in the connection / background services?

Oh yeah, and the speed limit there - luckily - is 60kmh, not 20 - just threw 20 there as an example :D

**Comment by juusomer** [comment]
Hah, alright.

From the logs it looks like your MQTT connection dies while the plot takes ages to do, after which the application starts to fetch the topic names again and encounters another (probably unrelated and temporary) error with the GraphQL API there. Technically we wouldn't need to get the topic names here again, so I could add some caching for those.

But that's really unrelated to the slowness issue here, which most probably was just related to temporary issues with either your internet connection or something in the background services that provide the maps.
